### ISSUE TITLE
Error when starting (Ubuntu 22.04)

### ISSUE THREAD

**Issue by netchron-personal** [CodeChefVIT/Quizzie#152]
I followed the "Instructions to run" but get an error:

root@server:~/quizzie# npm run dev

> backend@1.0.0 dev
> nodemon app.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
/root/quizzie/node_modules/passport-oauth2/lib/strategy.js:87
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/root/quizzie/node_modules/passport-oauth2/lib/strategy.js:87:34)
    at new Strategy (/root/quizzie/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at Object.<anonymous> (/root/quizzie/Backend/api/config/passport-setup.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/quizzie/app.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

Whan am I doing wrong?

**Comment by netchron-personal** [comment]
Any update here? Anyone still there to fix issues???
